<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Калькулятор</title>
</head>
<body>
<h1>Калькулятор</h1>
<div>
    <form action="/sum">
        <label>Число A
            <input name="numberA" placeholder="Введите число">
        </label>
        <br>
        <label>Число B
            <input name="numberB" placeholder="Введите число">
        </label>
        <input type="submit" value="Сложить">
    </form>
</div>
</body>
</html>